name: Build FAP
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  build-fap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {path: app}
      - uses: actions/checkout@v4
        with:
          repository: Next-Flip/Momentum-Firmware
          ref: e1784e7418d8b074e971983ceb6fef0f37e52ae4
          submodules: recursive
          path: momentum
      - run: make -C app check
      - run: ln -s "$GITHUB_WORKSPACE/app" momentum/applications_user/tonie_emulator
      - run: ./fbt fap_tonie_emulator
        working-directory: momentum
      - run: cp momentum/build/f7-firmware-C/.extapps/tonie_emulator.fap tonie_emulator.fap
      - uses: actions/upload-artifact@v4
        with:
          name: tonie_emulator
          path: tonie_emulator.fap
          if-no-files-found: error
